if(EXISTS "/Users/chaya/Github/libquicr/mlstest/quicr_mlstest_tests-b858cb2.cmake")
  include("/Users/chaya/Github/libquicr/mlstest/quicr_mlstest_tests-b858cb2.cmake")
else()
  add_test(quicr_mlstest_NOT_BUILT-b858cb2 quicr_mlstest_NOT_BUILT-b858cb2)
endif()
