name: Fuzz

on:
  push:
    branches: [ "main", "draft-18" ]
  pull_request:
    branches: [ "main", "draft-18" ]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Fuzz
      run: make fuzz
