name: Fuzz

on:
  push:
    branches: [ "main", "draft-18" ]
  pull_request:
    branches: [ "main", "draft-18" ]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Clang
      run: |
        wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 20
        echo "/usr/lib/llvm-20/bin" >> "$GITHUB_PATH"
    - name: Fuzz
      run: make fuzz
